#
# MODULE: PlayerBoost
#

[worldserver]

#######################################################################
# PlayerBoost.Enable
#     Active ou désactive le module.
#
#     Valeurs :
#         0 = Désactivé
#         1 = Activé
#
#     Défaut : 0
#######################################################################

PlayerBoost.Enable = 1


#######################################################################
# PlayerBoost.AttackSpeedBonus
#     Réduction du temps d'attaque du joueur (en %).
#
#     30 = attaques 30 % plus rapides.
#     S'applique à :
#       - arme principale
#       - arme secondaire
#       - arme à distance
#
#     Défaut : 0
#######################################################################

PlayerBoost.AttackSpeedBonus = 200


#######################################################################
# PlayerBoost.DamageReductionPct
#     Réduction des dégâts subis par le joueur (en %).
#
#     S'applique aux dégâts physiques et magiques.
#
#     20 = le joueur reçoit 20 % de dégâts en moins.
#
#     Défaut : 0
#######################################################################

PlayerBoost.DamageReductionPct = 50


#######################################################################
# PlayerBoost.PetAttackSpeedBonus
#     Réduction du temps d'attaque des familiers / gardiens.
#
#     S'applique notamment aux :
#       - familiers Chasseur
#       - démons Démoniste
#       - goules Chevalier de la Mort
#       - autres Guardians
#
#     Défaut : 0
#######################################################################

PlayerBoost.PetAttackSpeedBonus = 200


#######################################################################
# PlayerBoost.PetDamageReductionPct
#     Réduction des dégâts subis par les familiers / gardiens.
#
#     S'applique aux dégâts physiques et magiques.
#
#     Défaut : 0
#######################################################################

PlayerBoost.PetDamageReductionPct = 50


#######################################################################
# PlayerBoost.CastSpeedBonus
#     Réduction du temps de cast des sorts du joueur (en %).
#
#     30 = les sorts sont lancés 30 % plus vite.
#
#     Défaut : 0
#######################################################################

PlayerBoost.CastSpeedBonus = 200


#######################################################################
# PlayerBoost.PetCastSpeedBonus
#     Réduction du temps de cast des sorts des familiers et gardiens.
#
#     S'applique notamment aux :
#       - familiers Chasseur
#       - démons Démoniste
#       - goules Chevalier de la Mort
#       - autres Guardians
#
#     Défaut : 0
#######################################################################

PlayerBoost.PetCastSpeedBonus = 200